[package]
name = "wurstmineberg-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4"
async-graphql-rocket = "4"
lazy-regex = "2"
rocket = "0.5.0-rc.2"
thiserror = "1"

[dependencies.mcanvil]
git = "https://github.com/wurstmineberg/rust-anvil"
branch = "main"
