[package]
name = "wurstmineberg-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "6"
async-graphql-rocket = "6"
lazy-regex = "3"
rocket = "0.5"
thiserror = "1"

[dependencies.mcanvil]
git = "https://github.com/wurstmineberg/rust-anvil"
branch = "main"
